### ISSUE TITLE
Incorrect work with SoapClient in php8

### ISSUE THREAD

**Issue by KorDum** [php-soap/ext-soap-engine#1]
|    Q        |   A
|------------ | -----
| Version     | 1.0.0

### Support Question

Since php8 `SoapClient::__doRequest()` has `bool $oneWay`, not integer.

I have an error:
```
In AbusedClient.php line 64:                                                                                 
  SoapClient::__doRequest(): Argument #5 ($oneWay) must be of type bool, int given 
```

What am I doing wrong?

**Comment by veewee** [comment]
Can you share some code snippets on how you configured the client and how you call the webservice?

**Comment by KorDum** [comment]
Of cource, but it's better to look at the [official documentation](https://www.php.net/manual/en/soapclient.dorequest.php) :)
> 8.0.0 | The type of oneWay is bool now; formerly it was int.

https://github.com/php-soap/ext-soap-engine/blob/main/src/AbusedClient.php#L64

```php
$classMap = new ClassMapCollection(
    new ClassMap(/* ... */),
);

$engine = ExtSoapEngineFactory::fromOptions(
    ExtSoapOptions
        ::defaults($wsdl, [
            'soap_version' => SOAP_1_2,
            'location' => $location,
            'connection_timeout' => $timeout,
        ])
        ->withClassMap($classMap)
        ->disableWsdlCache()
);

// with caller from phpro/soap-client
$caller = new EventDispatchingCaller(
    new EngineCaller($engine),
    $eventDispatcher
);

$result = $caller('UniOperation', $parameters); // exception
```

**Comment by veewee** [comment]
Yeah we should probably move to bool argument, since the d package is php 8 only.
In the old implementation we needed to cover both cases. Hence the issue 

What I do not understand is the error you get. Since we have tests on all these components en i Aldo have it running in some projects myself.

I'dd suggest to use the psr-18 transport though, which is also standard in phpro/soap-client. It solves some common http issues in the soap client and doesn't execute that specific part of the abused client.

**Comment by KorDum** [comment]
> What I do not understand is the error you get

This one (at the very beginning of issue):

```
In AbusedClient.php line 64:                                                                                 
  SoapClient::__doRequest(): Argument #5 ($oneWay) must be of type bool, int given 
```

> Since we have tests on all these components

I have not found any tests covering this `doActualRequest` method, I guess that's why :)

> I'dd suggest to use the psr-18 transport though, which is also standard in phpro/soap-client

Ok, really, I thought that it would be possible to update the major version of the package with some little blood.

**Comment by veewee** [comment]
Allright, thanks for reporting. I'll try to fix it somewhere this week.

**Comment by veewee** [comment]
Fixed and released.
The code snippet above should now work whilst using the `ExtSoapClientTransport` as well.

https://github.com/php-soap/ext-soap-engine/releases/tag/v1.1.0
