### ISSUE TITLE
Injecting AnyType converter into soap response

### ISSUE THREAD

**Issue by rauanmayemir** [php-soap/ext-soap-engine#17]
Let's take an example of response XSD schema:

```
<xsd:complexType name="ResponseData">
  <xsd:sequence>
    <xsd:element minOccurs="0" name="data" type="xsd:anyType"/>
  </xsd:sequence>
</xsd:complexType>
```

`data` here is `anyType`, meaning the payload follows a different schema unknown to this particular WSDL.

For `decimal` or `dateTime`, I could create a custom `TypeConverterInterface` and it will perfectly convert the data into my wrapper classes.

But for some reason I can't make `ExtSoapDriver` hijack `anyType` and use my custom converter, it will just return `stdClass`. I remember seeing some issues where it was suggested to add some extra manipulation, but can't seem to find it anywhere.

I can't generate original bindings and hard code that `data` field to my custom class because it's a general data structure for transport and the actual class will depend on the domain (hence why I'm trying to find a way to set it dynamically).

**Comment by veewee** [comment]
Hello,

Thanks for reporting!

I've tried creating a type converter with following settings:

```php
'type_name' => 'anyType',
'type_ns' => 'http://www.w3.org/2001/XMLSchema',
```

and can confirm the `to_xml` and `from_xml` callbacks don't get triggered.

I think the typemap logic is not running on the any_type converter in PHP's Soap extension whilst 'guessing' the type:
https://github.com/php/php-src/blob/82e761eaacc49baf19a52d1cb4c100e299da12e2/ext/soap/php_encoding.c#L187

It's probably an uncovered case in PHP - in which we don't have any control.

Since this is in your response, you might want to go for the regular `stdClass` implementation and try to parse it from outside the soap-client instead? The soap-types are telling you it can be basically anything, so you'll have to parse it from outside the soap-client again  anyways.

**Comment by rauanmayemir** [comment]
Yeah, that’s what I likely have to do.
But what’s mildly annoying is that stdClass might lose some metadata I could use from the original xml.

I’ll look into abusing the already abused client. 😄

**Comment by veewee** [comment]
I don't think you can abuse it any further though. It's basically the base php soap cliënt turned outside in.
Meaning you already have control about everything you might want to be controlling.

It might make sense to just parse the XML directly from an http client in this case.
Or hou could use the engine to encode and transport - and do the decoding manually.
That way, you might have more control over the data 

But is all depends on your case of course.

**Comment by rauanmayemir** [comment]
I think I could add an event subscriber and catch the original raw response, from where I could extract data and parse according to my XSD schemas.

That actually sounds like a decent solution considering there's no way around ext-soap yet and it's better than traversing stdClasses.

**Comment by veewee** [comment]
Glad you found a decent solution!

Since encoding / decoding based on xsd meta will probably be the next big project for the php-soap project - feel free to share whatever you come up with.

**Comment by veewee** [comment]
Hello there @rauanmayemir ,

I wanted to get back to this issue:
We are finishing up v4 of the soap-client package which uses a new encoding system internally.
With this new system, you should be able to get around this issue more easily.

We are eager to receive some early feedback on this new release.
If you got some time, feel free to play around with the alpha version:


* Release: https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1
* Discussion: https://github.com/phpro/soap-client/discussions/527

**Comment by rauanmayemir** [comment]
This is actually the very first thing I'm eager to resolve. 😄
