### ISSUE TITLE
Incorrect work with SoapClient::__doRequest()

### ISSUE THREAD

**Issue by KorDum** [php-soap/ext-soap-engine#3]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.1.0

#### Summary

Hello! `SoapClient::__doRequest()` does return nullable string, but `AbusedClient::doActualRequest()` expects `string` always.

https://www.php.net/manual/en/soapclient.dorequest.php

```php
public SoapClient::__doRequest(
    string $request,
    string $location,
    string $action,
    int $version,
    bool $oneWay = false
): ?string
```

```
Soap\ExtSoapEngine\AbusedClient::doActualRequest(): Return value must be of type string, null returned
#0 php-soap/ext-soap-engine/src/Transport/ExtSoapClientTransport.php(26): Soap\ExtSoapEngine\AbusedClient->doActualRequest()
#1 php-soap/engine/src/SimpleEngine.php(25): Soap\ExtSoapEngine\Transport\ExtSoapClientTransport->request()
#2 phpro/soap-client/src/Phpro/SoapClient/Caller/EngineCaller.php(27): Soap\Engine\SimpleEngine->request()
#3 phpro/soap-client/src/Phpro/SoapClient/Caller/EventDispatchingCaller.php(30): Phpro\SoapClient\Caller\EngineCaller->__invoke()
```

#### How to reproduce

Sorry, I can't reproduce. You can replace to stub in test.

#### Expected behaviour

Without exception :)

**Comment by veewee** [comment]
Hello @KorDum,

Missed that one indeed. Can you validate if #4 fixes the issue for you? It used to work like that in the old phpro/soap-client.
 
The method returns `null` on timeouts etc right? Will try to validate myself as well later this week.

Reported the issue to psalm as well. Since I removed the cast because they expect the type to be string.

**Comment by KorDum** [comment]
Great! Looks like true.

It was possible without casting with the usual condition `?? ''`. But it will work like that of course.

> The method returns null on timeouts etc right?

Seems to be

**Comment by veewee** [comment]
Alright. Tested it myself as well by setting the `default_socket_timeout` to 0.

Merged and released:
https://github.com/php-soap/ext-soap-engine/releases/tag/v1.1.1

Thanks for reporting! Hope it works again like you'dd expect from now on :)
